#ifndef COMMON_H
#define COMMON_H

#define ADDRESS_SOCKET "socket_address"
#define MAX_MESSAGE_BUFFER_SIZE 200
#define MAX_THREADS 200

#define NUMBER_OF_WORKER_THREADS 7

#define MEN_WC_THREAD_1 0
#define MEN_WC_THREAD_2 1
#define WOMEN_WC_THREAD_1 2
#define WOMEN_WC_THREAD_2 3
#define DEF_WC_THREAD 4
#define TOBOGAN_PEQUENO_THREAD 5
#define TOBOGAN_GRANDE_THREAD 6

#endif
